import logging
import platform

LOGLEVEL = logging.INFO
NO_OVERFLOW = False
RECORD = False
QUIET = False
PSYCHO_MODE = False

SENSITIVITY = 1
FRAMES_PER_BUFFER = 1024
RATE = 44100
CHANNELS = 1
FORMAT = "Int16"
PICKING_MODE = "cycle"

if platform.system() == "Darwin":
    PLAYER = "/Applications/VLC.app/Contents/MacOS/VLC --play-and-exit -"
else:
    PLAYER = "aplay"

PLAYER_INPUT = "arg"

LOW_SOUNDS = []
LOW_FREQUENCY = 80
MEDIUM_SOUNDS = []
MEDIUM_FREQUENCY = 160
HIGH_SOUNDS = []
HIGH_FREQUENCY = 320

LOW_ABOVE = LOW_THRESHOLD = 100
MEDIUM_ABOVE = MEDIUM_THRESHOLD = 200
HIGH_ABOVE = HIGH_THRESHOLD = 300


# MITIGATE
BEAT_EVERY = 0
BEAT_RANDOM = False
BEAT_MIN = BEAT_MAX = BEAT_EVERY

BEAT_SOUND = None
BEAT_FREQUENCY = 60


# VISUALISE
AMPLITUDE_SYMBOL = "="
FREQUENCY_SYMBOL = "-"
PEAK_SYMBOL = "|"

QUIET_COLOR = None
LOW_COLOR = "blue"
MEDIUM_COLOR = "yellow"
HIGH_COLOR = "red"

DEFAULT_TERM_WIDTH = 80
